### ISSUE TITLE
How can custom Openshift Route TLS Termination for each Deployment Component

### ISSUE THREAD

**Issue by wdrdres3qew5ts21** [kiegroup/kie-cloud-operator#686]
Hello I had question about Openshift Route that Generated from Business Automation Operator is there any reason why every Route that sending traffic to Service is need to using Openshift Route TLS "Passthough" only ?
Because I want to using TLS Edge Termination but I can not modify anything (due to Operator will bring back stable state)

Operator SDK Source Code [config/7.11.1/common.yaml Line-406](https://github.com/kiegroup/kie-cloud-operator/blob/6efb8774e051a9411e1dd8f7a84e5401e5d66134/config/7.11.1/common.yaml#L406)

![image](https://user-images.githubusercontent.com/25000903/135305359-80179c8f-20c0-48d2-92c3-bc355c283845.png)

From I see in source Code and in Operator I can't  modify or customize anything relate to Openshift Route that will using for Business Central, KIE Server, Dashboard, etc. 
Because currently if I want to using TLS Termination with "Edge" strategy 

![image](https://user-images.githubusercontent.com/25000903/135305958-1e4e34c0-10bd-43f0-9372-8dab72518d08.png)

I must manually create another Route by myself then it will cause "duplicated Route" as you see in my picture. 

![image](https://user-images.githubusercontent.com/25000903/135303513-e7a44e3c-8486-4294-890d-012c93f9cc71.png)

Also because this Kubernetes Resource is created by Operator so I can not modified or delete anything I just need to accept that I will have duplicated route and also required to expose the Route Endpoint every time ? 

![image](https://user-images.githubusercontent.com/25000903/135304761-4aab1ff8-1caf-453c-8ef1-bf0c8d47f75f.png)

Do I missing anything in the Documentation ? 
Thank you for helping !

**Comment by spolti** [comment]
hi @wdrdres3qew5ts21, we do use pass-trough termination because the SSL, in this case, is handled bu JBoss EAP by default.
You can edit the config map that you mentioned that the configuration will be applied by the operator.

However, I would kindly suggest you to open a ticket at Red Hat Customer Portal for further assistance on this.

Thank!

**Comment by wdrdres3qew5ts21** [comment]
Thank you ! It seem like I can edit ConfigMap manually to make Operator stop bring back the change that I made to Openshift Route now I can using Route with Edge Termination :D
It first time that I know that we can modify Operator configuration too :)
Close case.
